### ISSUE TITLE
sample ,run_all.py, get error "Writing hexmini.tmx", in osx

### ISSUE THREAD

**Issue by liu0fanyi** [BorisTheBrave/DeBroglie#12]
```
...
Writing docs/output/pathway_overlapping.png
Running docs/hexmini.json
Reading docs/hexagonal-mini.tmx
Processing docs/output/hexmini.tmx
Writing docs/output/hexmini.tmx

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DeBroglie.Topo.TopoArray1D`1.Get(Int32 index) in /Users/mac/game/DeBroglie/DeBroglie/Topo/TopoArray1D.cs:line 23
   at DeBroglie.TilePropagator.<>c__DisplayClass41_0.<ToArray>b__0(Int32 index) in /Users/mac/game/DeBroglie/DeBroglie/TilePropagator.cs:line 548
   at DeBroglie.Topo.TopoArray.CreateByIndex[T](Func`2 f, ITopology topology) in /Users/mac/game/DeBroglie/DeBroglie/Topo/TopoArray.cs:line 105
   at DeBroglie.TilePropagator.ToArray(Tile undecided, Tile contradiction) in /Users/mac/game/DeBroglie/DeBroglie/TilePropagator.cs:line 544
   at DeBroglie.Console.Export.TiledMapExporter.Export(TileModel model, TilePropagator tilePropagator, String filename, DeBroglieConfig config, ExportOptions exportOptions) in /Users/mac/game/DeBroglie/DeBroglie.Console/Export/TiledMapExporter.cs:line 25
   at DeBroglie.Console.Export.Exporter.Export(TileModel model, TilePropagator tilePropagator, String filename, DeBroglieConfig config, ExportOptions exportOptions) in /Users/mac/game/DeBroglie/DeBroglie.Console/Export/Exporter.cs:line 30
   at DeBroglie.Console.ItemsProcessor.ProcessItem() in /Users/mac/game/DeBroglie/DeBroglie.Console/ItemsProcessor.cs:line 201
   at DeBroglie.Console.ItemsProcessor.Process(String filename) in /Users/mac/game/DeBroglie/DeBroglie.Console/ItemsProcessor.cs:line 292
   at DeBroglie.Console.Program.Main(String[] args) in /Users/mac/game/DeBroglie/DeBroglie.Console/Program.cs:line 18
Traceback (most recent call last):
  File "run_all.py", line 11, in <module>
    subprocess.check_call(de_broglie + [filename])
  File "/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dotnet', 'run', '--project', '../DeBroglie.Console', '--no-launch-profile', '--', 'docs/hexmini.json']' returned non-zero exit status 134.
```

**Comment by BorisTheBrave** [comment]
Thanks for the report.
