### ISSUE TITLE
Deque is empty

### ISSUE THREAD

**Issue by Sajdkick** [BorisTheBrave/DeBroglie#21]
I sometimes get the exception
`System.Exception: Deque is empty
   at DeBroglie.Wfc.WavePropagator.Step()
   at DeBroglie.Wfc.WavePropagator.Run()
   at DeBroglie.TilePropagator.Run()`

This is on an AdjecentModel with one CountConstraint and a manual Select() to insert '0' tiles on the border. It's pretty rare though, have happened twice over 2 hours of playing around.

**Comment by BorisTheBrave** [comment]
That sounds like it needs fixing, but I don't think I can proceed without a test case. (note you can fix the random seed to get reproducible results).

**Comment by Sajdkick** [comment]
Awesome, when it shows up again I'll try to get a test case for you :)

**Comment by Sajdkick** [comment]
Encountered it again, its very rare though and this is the first time after reporting. How would i go about fixing the seed?

**Comment by Sajdkick** [comment]
I got it to happen consistently.

```
DeBroglie.Tiled.TiledMapImporter importer = new DeBroglie.Tiled.TiledMapImporter();

var sampleSet = importer.Load("Deque Map Crash");

// Specify the model used for generation
var model = new OverlappingModel(2, 2, sampleSet.Samples[0].Topology.Depth == 1 ? 1 : 2);

model.AddSample(sampleSet.Samples[0]);

// Set the output dimensions
var topology = new GridTopology(10, 10, sampleSet.Samples[0].Topology.Depth, false);

Random random = new Random(0);

var options = new TilePropagatorOptions
{
    Constraints = new[] { new DeBroglie.Constraints.CountConstraint
    {
        Tiles = new[] { new Tile(129) }.ToHashSet(),
        Count = 5,
        Comparison = DeBroglie.Constraints.CountComparison.Exactly,
        Eager = false,
    } },
    BackTrackDepth = 1000,
    RandomDouble = () => { return random.NextDouble(); }
};

// Acturally run the algorithm
var propagator = new TilePropagator(model, topology, options);
propagator.Run();
```

If I run this while loading this json map https://pastebin.com/CBhymARK i get the error everytime.

**Comment by BorisTheBrave** [comment]
Unfortunately, this isn't reproducing anytning for me. I've tried many seeds, and there are no issues.

Are you using the latest version, read from the master branch?

Otherwise, I'm afraid you may need to try again with a nother random generator (.e.g https://gist.github.com/kaustav-das/cf6b60638e62abb0394737f19f2fcf03)
