### ISSUE TITLE
DeBroglie.Console crashes when following the Introduction tutorial

### ISSUE THREAD

**Issue by giovinazzo-kevin** [BorisTheBrave/DeBroglie#5]
I get a NPE whenever I try to run the executable (2.0 release) by dragging the following JSON file into it:

```json
{
    "src": "sewers.png",
    "dest": "generated-sewers.png",
    "model": {
        "type": "overlapping",
        "n": 3
    },
    "periodicInput": true,
    "periodic": true,
    "symmetry": 8
}
```
This is the stack trace:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DeBroglie.Console.Export.BitmapExporter.Export(TileModel model, TilePropagator propagator, String filename, DeBroglieConfig config, ExportOptions exportOptions) in C:\Users\Adam\Documents\Programming\Programming 2018\DeBroglie\DeBroglie.Console\Export\BitmapExporter.cs:line 66
   at DeBroglie.Console.Export.Exporter.Export(TileModel model, TilePropagator tilePropagator, String filename, DeBroglieConfig config, ExportOptions exportOptions) in C:\Users\Adam\Documents\Programming\Programming 2018\DeBroglie\DeBroglie.Console\Export\Exporter.cs:line 17
   at DeBroglie.Console.ItemsProcessor.ProcessItem() in C:\Users\Adam\Documents\Programming\Programming 2018\DeBroglie\DeBroglie.Console\ItemsProcessor.cs:line 343
   at DeBroglie.Console.ItemsProcessor.Process(String filename) in C:\Users\Adam\Documents\Programming\Programming 2018\DeBroglie\DeBroglie.Console\ItemsProcessor.cs:line 458
   at DeBroglie.Console.Program.Main(String[] args) in C:\Users\Adam\Documents\Programming\Programming 2018\DeBroglie\DeBroglie.Console\Program.cs:line 16
```

This bug **does not** happen with the 1.0 release, so I suppose that the [introduction ](https://boristhebrave.github.io/DeBroglie/articles/index.html) still needs to be updated.

**Comment by BorisTheBrave** [comment]
Thanks for the report - it's easy to forget to update these things. It shouldn't give you a NullReferenceException in any case.

**Comment by BorisTheBrave** [comment]
I've made a new release [v0.2.1](https://github.com/BorisTheBrave/DeBroglie/releases/tag/v0.2.1) which fixes the issue. Please try it out.

**Comment by giovinazzo-kevin** [comment]
Yup, it works on my end as well. Thank you for addressing the issue so quickly! I hadn't noticed the notification.
